id: IA7EC0110
source: https://github.com/Esukhia/chojuk-alignement/tree/master/D3875final
source_file: null
initial_creation_type: input
imported: '2022-07-27T11:37:54.475850'
last_modified: '2022-07-27T11:37:54.475865'
parser: null
source_metadata:
  title: ཐུན་མོང་གི་རྩ་བ།
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
